- .gitignore
- outsource/Config.py
- outsource/Outsource.py
- outsource/RunConfig.py
- outsource/rundb.py
- outsource/workflow/paxify.py
- outsource/workflow/run-pax.sh
- tests/submit-test-workflow.py
This replaces cax-process with paxify.py which is copied to the worker in similar way to determine_rse (for the moment at least - can change later). It also adds the RunConfig class which is passed as input to Outsource. 
It's not quite working fully, but I think it's close.
> Replace cax-process and add runconfig

- outsource/Outsource.py
- outsource/RunConfig.py
- outsource/workflow/combine-wrapper.sh
- outsource/workflow/combine.py
- outsource/workflow/pegasus.conf
- outsource/workflow/upload.py
- tests/submit-single-test-workflow.py
This is somewhat large PR that includes generalizations and streamlining of the workflow in a few places.
- Outsource now would look in the utilix config for what data it should try to process. The main arguments given are then a context name and straxen version, which outsource uses to determine what data needs to be processed. 
-  Code is cleaned up so that we don't have to do copy + paste for the different processing levels. 
- The combine job is optimized a bit so that we don't have to move/copy data around during the job, like we did before. 
I'm sure there are others, but those are the main things off the top of my head. Nearly every file changed in some way.
> Generalize processing layers and add straxen version information

- outsource/Outsource.py
- outsource/workflow/combine.py
- outsource/workflow/pegasus.conf
- outsource/workflow/pre-flight-wrapper.sh
- outsource/workflow/pre-flight.py
- outsource/workflow/runstrax.py
- setup.py
Here's a reasonably large update. I just tested it on a large amount of data and it worked quite well!
- The main change is it allows you to process peaklets directly from raw_records on the per-chunk jobs. We create records in the process and upload it to rucio. The removes an extra data transfer which is nice, and reduces the number of jobs required for a single workflow substantially. 
- I also added a `outsource` command so that you can easily submit workflows for individual runs or lists of runs. There's definitely more we can do here, but it's a convenient start. 
- Data for high level stuff gets copied to Dali automatically. And there's some runDB changes etc.
- I reduced the max_jobs to 300 because I was seeing rucio problems last night during the large submission.
> Raw_records and records on same job

- outsource/Outsource.py
Trying to bypass tricky feature related to `event_info` described [here](https://github.com/XENONnT/cutax/issues/268). Otherwise you run into this issue:
```
Traceback (most recent call last):
File "/home/yuanlq/.local/bin/outsource", line 7, in <module>
exec(compile(f.read(), __file__, 'exec'))
File "/home/yuanlq/software/outsource/bin/outsource", line 233, in <module>
main()
File "/home/yuanlq/software/outsource/bin/outsource", line 229, in main
outsource.submit_workflow()
File "/home/yuanlq/software/outsource/outsource/Outsource.py", line 181, in submit_workflow
wf = self._generate_workflow()
File "/home/yuanlq/software/outsource/outsource/Outsource.py", line 284, in _generate_workflow
start_valid, end_valid = self.dtype_validity(dtype)
File …
```
> Workaround for `cutax v1.15.0`

- bin/outsource
- outsource/Outsource.py
Related to [this issue](https://github.com/XENONnT/cutax/pull/269), but it is always good to make sure our registered plugins in `outsource` is as few as necessary. If we don't remove the cuts, we will have super slow `st.provided_dtypes` and `straxen.get_corrections.get_cmt_options(st)` which leads to 15 min to submit a single job.
> Removed cuts from registered plugin

- bin/outsource
Sometime we still want to process in online context so messy should be included.
> removed messy from exclude_modes

- outsource/Outsource.py
As @rynge pointed out, 
```
condorpool.add_profiles(Namespace.CONDOR, key='periodic_remove',
value="((JobStatus == 2) && ((CurrentTime - EnteredCurrentStatus) > 18000)) || "
"((JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 30)) "
)
```
was actually a bug, since `JobStatus==2` means running instead of IDLE.
> Removed buggy profile

- README.md
- outsource/RunConfig.py
So now we can test how we can accelerate `peaklets` jobs with smaller RAM!
> `chunks_per_job` into config

- outsource/Outsource.py
In #80 there is a bug introduced. After reading again I realize this is not how we can control the source of `raw_records`. The current implementation will actually shoot error for some runs. 
Also, it turns out that any configuration in current `outsource`+`straxen`+`xe-admix` will NOT take raw_records from SDSC_NSDF_USERDISK, because of this this chain [admix](https://github.com/XENONnT/admix/blob/d7ac0d106672b10f47e3a4c45560a2eca214755e/admix/downloader.py#L61)->[straxen](https://github.com/XENONnT/straxen/blob/6bddda5679ecb5cb2c718912242173c24638e989/straxen/storage/rucio_remote.py#L125C36-L125C49)->[outsource](https://github.com/XENONnT/outsource/blob/bb89bb4cc832b618ec75eb3c8e658dc8e27a05da/outsource/workflow/runstrax.py#L261) Unless UC_OSG_USERDISK has no copy of raw_records for …
> Fixed abuse of `raw_records_rse`

- outsource/Outsource.py
Still cannot specify from which site admix.download will do for the raw_records. but in the following cases, we are doing better:
1. If have `raw_records` available at both `SOMEWHERE` and `SURFSARA_USERDISK`, and we specified `raw_records_rse = SURFSARA_USERDISK`, the desired sites will be only `SURFSARA_USERDISK `.
2. If have `raw_records` available at both `SDSC_NSDF_USERDISK` and `SURFSARA_USERDISK`, and we specified `raw_records_rse = SDSC_NSDF_USERDISK`, the desired sites will be only `NONE` (because `'SDSC_NSDF_USERDISK': {'expr': 'GLIDEIN_Country == "US"'}` in `_rse_site_map`).
> Improved usage of `raw_records_rses`

- outsource/workflow/runstrax.py
To save memory, by avoiding staging heavy middle steps in RAM. Save the heavy middle steps first.
> Prioritize heavy low level types in runstrax

- outsource/RunConfig.py
Expected behavior: if the run doesn't have `peak_basics`, outsource will process this run.
> Added peak_basics into to-check in RunDB

- outsource/RunConfig.py
This missing comma explains why we had lots of empty workflow...
> Debug missing comma in RunConfig

- outsource/workflow/combine.py
- outsource/workflow/strax-wrapper.sh
So we don't saturate disks with unnecessary data types.
- Delete `records` in `strax-wrapper` after processing `peaklets` jobs
- Force not uploading `records` to rucio
> No records or records_nv to upload in rucio

- outsource/workflow/combine.py
- outsource/workflow/runstrax.py
Before this PR, a typical TPC workflow's event job will process in the following order
```
peaklet_classification, merged_s2s, peaks, peak_basics, peak_positions_gcn, peak_positions_mlp, peak_positions_cnn, peak_proximity, peak_positions, events, energy_estimates, corrected_areas, event_positions, event_basics, distinct_channels, event_info, event_ambience, event_area_per_channel, event_ms_naive, event_top_bottom_params, peak_s1_positions_cnn, event_pattern_fit, event_info_double, event_shadow, cuts_basic
```
There are two issues:
1. `events` is never computed directly as a target, because of the `save_when == NEVER` nature. @dachengx has pointed out that without saving `events` we might be vulnerable to [chunk merging problem](https://xenonnt.slack.com/archives/C016DM0JPK9/p17062256346280 …
> Save `events` and changing order

- outsource/Outsource.py
- outsource/workflow/combine.py
- outsource/workflow/runstrax.py
First success to solve #131 and #126:
```
/scratch/yuanlq/workflows/runs/straxen_v2.2.0/xenonnt_offline/sr1_th232_events_test_4/
```
See here for details of an example, where `'veto_regions-hwcemk7dbt-metadata.json'` was an orphan file.
```
--------------------------
Checking if chunk length is agreed with promise in metadata for 051432-veto_regions-hwcemk7dbt
The chunk length is agreed with promise in metadata.
--------------------------
Trying to upload finished_data/051432-veto_regions-hwcemk7dbt to UC_MIDWAY_USERDISK
Pre-uploading data to rucio!
File 051432-veto_regions-hwcemk7dbt could not be attached
File 051432-pulse_counts-hwcemk7dbt could not be attached
File 051432-peaklets-euocvpkv3y could not be attached
File 051432-lone_hits-euocvpkv3y could not be attached
=== Preuploading …
```
> Preupload to avoid rucio orphan files

- outsource/workflow/runstrax.py
This should be a new problem after rucio update, where the function `rucio_client.list_dids` has been changed.
```
Traceback (most recent call last):
File "/srv/pegasus.vUfROFZUo/./runstrax.py", line 617, in <module>
main()
File "/srv/pegasus.vUfROFZUo/./runstrax.py", line 527, in main
existing_files = [f for f in admix.clients.rucio_client.list_dids(scope, {'type': 'file'}, type='file')]
TypeError: list_dids() got an unexpected keyword argument 'type'
```
Let's try if it works to remove the whole attach part.
> Removed attach process

- outsource/workflow/runstrax.py
- outsource/workflow/strax-wrapper.sh
This is a byproduct of exploration in #143 . 
In the past we were always regenerating `.dbtoken` on job node, because of the wrong `$HOME` directory to search for it. Now we overwrites `$HOME` so it can find the uploaded `.dbtoken` and avoid regeneration. Meanwhile, we added a bit more debug info regarding RunDB API, and turned off the not working `nmap` test.
> Avoid regeneration of `.dbtoken` on job node

- outsource/Outsource.py
- outsource/workflow/combine-wrapper.sh
- outsource/workflow/combine.py
Similar as aftershock of #144, initialization of `DB` will fail under `rundb_api_url = http://xenon-runsdb.grid.uchicago.edu:80`. So we have to correct the usage of `.dbtoken`.
> Debug combine wrapper

- outsource/Outsource.py
Since `latest` might be a bit too risky when processing, using `development` to reprocess is usually a better choice.
> Changed default to development

- bin/outsource
Historically, this part was introduced to avoid some bad inconsistency in straxen versions ago. No longer needed.
> Remove event_info re-registering

- outsource/Outsource.py
This function has been retired because of the retired grid-proxy-info command in ap23 since June 2024. We still want it again once we have a new equivalent function.
> Retire grid proxy info

- outsource/Outsource.py
A followup in #155. We just reinstalled the `grid-proxy-info` on ap23.
> Put back x509 proxy check

- outsource/workflow/pegasus.conf
Counter this new issue
```
"stage_out_local_staging-davs_0_11.out.005" 1104L, 100151B                                                                                    1,1           Top
File "/usr/lib64/python3.9/site-packages/Pegasus/cli/pegasus-integrity.py", line 610, in <module>
main()
File "/usr/lib64/python3.9/site-packages/Pegasus/cli/pegasus-integrity.py", line 597, in main
current_sha256 = generate_sha256(fname)
File "/usr/lib64/python3.9/site-packages/Pegasus/cli/pegasus-integrity.py", line 218, in generate_sha256
tc.run()
File "/usr/lib64/python3.9/site-packages/Pegasus/tools/worker_utils.py", line 154, in run
raise RuntimeError(
2024-06-11 15:32:10,400    INFO:  /usr/bin/openssl: symbol lookup error: /usr/bin/openssl: undefined symbol: BIO_new_dgram_sctp, version …
```
> Temporary bypassing integrity check in pegasus

- outsource/Outsource.py
When running in debug mode (we have to because of the [rucio direct upload issue unresolved](https://github.com/XENONnT/outsource/issues/137) ), it is a pain that we keep saturating our scratch folder locally. Since there is no more than two people running outsource, we can just make sure users delete stuff on davs constantly on their own, and it shall be safe.
> No more local output

- outsource/Outsource.py
- outsource/workflow/runstrax.py
This is mandatory in new OSG situation (see [here](https://github.com/XENONnT/alea/pull/178) for a similar issue).
- Make sure `runstrax.py` always use single thread processor
- Give combine jobs 4 CPUs, in case we fail the CPU excessive usage error
> Testing single thread processor

- outsource/Outsource.py
- outsource/workflow/pegasus.conf
- Reduce transfer threads to follow the new OSG rules on CPU excessive usage
- Add one more core to event level jobs to see if it reduces problems in excessive usage
> Reduce transfer thread and one more core in event level jobs

- outsource/Outsource.py
- outsource/workflow/combine-wrapper.sh
- outsource/workflow/strax-wrapper.sh
Otherwise, you will fail at running `runstrax.py` if you don't have production proxy. This was too overkill before, and now everyone can use the grid to process things in debug mode.
> No longer need production if you don't even try to upload to rucio

- README.md
- outsource/config.py
- outsource/outsource.py
Similar to https://github.com/XENONnT/alea/pull/201
> Configuration of disk should be in MB

- README.md
- outsource/outsource.py
- outsource/workflow/combine-wrapper.sh
- outsource/workflow/install.sh
- outsource/workflow/process-wrapper.sh
Depends on https://github.com/XENONnT/utilix/pull/125.
1. `Outsource.make_tarballs` will make tarball of `strax`, `straxen`, and `cutax` if they are in editable user-installed mode.
2. `outsource/workflow/install.sh` will install them if a tarball is found.
> Tarball strax(en) and cutax for later user installation

- README.md
- outsource/scripts/submit.py
- outsource/submitter.py
Close: https://github.com/XENONnT/outsource/issues/186
If using `--local_transfer`, the processed data will be transferred back to the workflow folder in `/xenon/scratch/`whoami``.
For example, `outsource --context xenonnt_offline --xedocs_version global_v16 --image el9.2024.09.1 --run 53018 --ignore_processed`.
This is accomplished by:
1. set `output_sites` argument of job submission to `"local"` if `local_transfer` is `True`, otherwise `"staging-davs"`.
2. if `local_transfer` is `False`, we do not need to initialize `"local"` site.
> Transfer data to local after processing

- outsource/submitter.py
Add a list of packages that should be user-installed
Close: https://github.com/XENONnT/outsource/issues/74
This PR is implemented as https://github.com/XENONnT/outsource/issues/74#issuecomment-2378272461.
1. If you want to self-install a package, put it in the `user_install_package` section of  `Outsource` in the XENON_CONFIG configuration.
2. If you want to check whether a package is self-installed but not included in the workflow(will not installed on the computing node), put it in the `check_user_install_package` section of  `Outsource` in the XENON_CONFIG configuration.
Depends on https://github.com/XENONnT/utilix/pull/133
> Check if there is no crucial user installed package

- outsource/workflow/combine.py
- outsource/workflow/process.py
- outsource/workflow/untar.sh
Close: https://github.com/XENONnT/outsource/issues/93
1. Download `raw_records*` from `raw_records_rse`.
2. Download other things if not `ignore_processed`.
> Download `raw_records*` from only `raw_records_rse`

- outsource/workflow/process-wrapper.sh
Close: https://github.com/XENONnT/outsource/issues/205
Thank @juehang and @rynge  for looking for the reason and providing the solution.
For the issue of JAX, unfortunately, this TODO is still a TODO: https://github.com/openxla/xla/blob/8d7f72345ce58ce959dcc99f2b1a13e5c672b3e9/xla/pjrt/utils.cc#L817.
Related [slack thread](https://xenonnt.slack.com/archives/C016UJZ090B/p1728527855644359)
> Limit the number CPU usage of JAX and TensorFlow

- outsource/config.py
- outsource/scripts/submit.py
- outsource/submitter.py
- outsource/utils.py
- outsource/workflow/combine.py
- outsource/workflow/process.py
For example, event_pattern_fit depends on `event_area_per_channel`:
https://github.com/XENONnT/straxen/blob/764f14cbc16c8633e176ca8c0a93c589293c24e0/straxen/plugins/events/event_pattern_fit.py#L15. `event_area_per_channel` is not always saved, but while processing `event_area_per_channel`, `event_n_channel` will be saved. In this case, even though `event_n_channel` is lower than `event_pattern_fit`, we should not directly process `event_n_channel`. Instead, we should process `event_area_per_channel` first.
`utils.get_processing_order` does this.
> Optimize the order of data_types in processing

- outsource/submitter.py
- outsource/workflow/combine-wrapper.sh
- outsource/workflow/process-wrapper.sh
Sometimes, a "combine" job also uses more than one CPU. This is CPU dependent so it will not always happen.
This PR limits the CPU for all jobs to one.
> Set environmental variable of CPUs usage for all jobs

- README.md
- outsource/scripts/submit.py
Following proposed change https://github.com/XENONnT/outsource/pull/220#issuecomment-2415628416
I believe a simple forbidden will prevent abuse and make sure the human processor is sober.
> Forbid using development container

- .pre-commit-config.yaml
- README.md
- outsource/scripts/submit.py
- outsource/submitter.py
1. Force renew the `.dbtoken` before submission of not `--keep_dbtoken`.
2. Copy `.dbtoken` to `Submitter.generated_dir` to avoid its change after the job submission.
> Force renew `.dbtoken` before workflow submission

- README.md
- outsource/scripts/submit.py
- outsource/submitter.py
- outsource/workflow/combine.py
- outsource/workflow/process.py
1. Add `--stage_out_lower` to download the lower level reprocessing result.
2. Add `--keep_raw_records ` to keep the downloaded `raw_records*`.
> Allow staging-out lower `data_types` and keeping downloaded `raw_records*`

- outsource/config.py
We limited the site of RSE of `RucioRemoteFrontend` to be `raw_records_rse` in https://github.com/XENONnT/outsource/blob/4f6e5b07e7bd65a07b8e4866c7cbc1d13ddf1b60/outsource/utils.py#L38. So we also need to decide whether the dependency exists based on `raw_records_rse`.
> Decide whether the dependency exists based on specified RSE

- outsource/workflow/combine-wrapper.sh
- outsource/workflow/process-wrapper.sh
- outsource/workflow/test_resource_usage.py
Previously when there are multiple json files existed, you might see errors like:
```
bash: [: 053018_process_storage_usage_lower_tpc_0_1.json: binary operator expected
```
.
> Fix bug when multiple json files exists

- outsource/meta.py
Fortunately, the lower-level memory usage will be similar to TPC runs.
But I still increased the memory requirement of lower-level processing.
> Assign the resources usage of LED calibration

- outsource/config.py
Sometimes the data can exist on multiple RSEs. But usually, we should send the job to nodes connected to `UC_OSG_USERDISK`. This PR make sure that the first RSE in `raw_records_rses` is priorities.
> Prioritize the first assign RSE

- outsource/config.py
- outsource/meta.py
- outsource/submitter.py
- outsource/utils.py
Hey all, 
here some small modifications to outsource from a small test I tried to run (without knowing much). 
- Allow for unregistered plugins in the hardcoded  PER_CHUNK_DATA_TYPES, DETECTOR_DATA_TYPES: because some plugins can be non registered in the used straxen version (I had it now for the peaklet posrec for example), I now filter them and simply drop the extra plugins. 
- Update the RSE desired sites list, as all the nikhef and surfsara locations are basically interchangeable (I use now only NL ase country requirement - tested and works.)
- Update comment on desired sites list: this is something that constrains where we can run the jobs based on the RSE that we put in the xenon config. I thing we could just get rid of this functionality probably. 
- When assigning resources the …
> Small updates and fixes

- outsource/scripts/raw_records_location.py
Sometimes you can not find where is the `raw_records*`, so you will use `raw_records_location.py run_id`.
> Print locations of `raw_records*`

- outsource/config.py
- outsource/meta.py
Also add a upper limit of memory usage
Depends on
1. https://github.com/AxFoundation/strax/pull/942 + https://github.com/XENONnT/straxen/pull/1508
2. https://github.com/AxFoundation/strax/pull/943
After these optimizations, https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:straxen:optimize_outsource_resources#optimized_memory_usage is achieved.
> Lower memory usage of lower level processing

- outsource/config.py
- outsource/meta.py
But the coefficients `[k, b] = [7.0, 0.8e3]` are a bit high. It would be good to optimize the memory usage so that 7.0 reduces to ~4.
Reference: https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:straxen:optimize_outsource_resources#memory_usage_for_led_calibration_runs
> Set special memory usage for LED calibration runs

- outsource/config.py
Somehow if these constraints are not added, the rucio `raw_records` will be invisible, e.g. `063518`.
> Add constraint for `SURFSARA2_USERDISK`

- outsource/config.py
Previously the disk requirement is determined purely by the size of `raw_records`. And when the size of `raw_records` is ~0, the required disk will also be ~0. So this 200MB lower limit is applied to hold the tarballs of software and other auxiliary files.
> Set lowest disk requirement as 200MB

- outsource/config.py
- outsource/meta.py
Be compatible with https://github.com/XENONnT/straxen/blob/bf6e7535912ced9bfa61d90b182086716a606267/straxen/plugins/raw_records_coin_nv/nveto_recorder.py#L82.
Similar to https://github.com/XENONnT/outsource/pull/257.
> Piecewise function for NV disk usage again

- outsource/submitter.py
- outsource/submitters/slurm.py
When no per-chunk processing is needed, the combine job depends on nothing. So that is a combine-only workflow. The per-chnk results should already be in `strax_data_osg_per_chunk`.
> Add special input path for combine-only job

- outsource/config.py
- outsource/utils.py
1. By setting `no_remote = True`, no remote backend will be added
2. By setting `no_per_chunk = True`, not lower level jobs will be submitted
> Completely local reprocessing and no-per chunk reprocessing

- outsource/submitter.py
In both relay and resubmit (and relay & resubmit) mode, we should allow the existing workflow directory.
> Fix bug in resubmit mode
