XENONnT/outsource

outsource/Outsource.py
outsource/RunConfig.py
outsource/main.py
outsource/workflow/combine-wrapper.sh
outsource/workflow/combine.py
outsource/workflow/pegasus.conf
outsource/workflow/runstrax.py
outsource/workflow/strax-wrapper.sh

This uses cutax (via tarballs), installs it on the job, and then uses the context there instead of straxen.

Use cutax contexts

---

outsource/processing_requests.py

Add helper functions for submitting jobs based on processing requests made by analysts.
Still unsure this is the right place for this code but at least we can start testing this way.

Processing requests

---

outsource/Outsource.py

Advised by @rynge. Simply added ProjectName.

Add project name

---

bin/outsource

Runlist bug fixed

---

outsource/Outsource.py

Advised by @rynge, trial to fix #29.

Fixed PegasusClientError

---

outsource/RunConfig.py

So that we don't download from non-OSG locations, we will then be not affected by problematic rses.

hardcode to do standalone_download

---

bin/outsource

If there are some runs not processable, it will be printed.

Debug info for `find_data`

---

outsource/Shell.py

[Related issue ](https://github.com/fkie/multimaster_fkie/issues/149)

Changed to is_alive instead of isAlive

---

outsource/Outsource.py
outsource/workflow/combine.py
outsource/workflow/pegasus.conf

On the way to tackle #57 
- More verbosity
- Reduce number of retrial to accelerate failures

Debug combine job failure

---

bin/outsource
outsource/Outsource.py

Also increased memory/disk for event level job

`raw_records` RSE surgery

---

README.md
outsource/Outsource.py

Advised by @ahiguera-mx . For testing, it might be helpful to specify one single site. Here we implemented a config in `.xenon_config` and we can use it to specify the site.

This site only

---

README.md
outsource/RunConfig.py

* chunks_per_job in config
* updated doc

`chunks_per_job` into config (#77)

---

outsource/workflow/combine.py

- Removed useless chunk size configuration
- Added `merged_s2s` to `peaklets_rse`

Combine job clean up

---

bin/outsource
outsource/RunConfig.py
outsource/workflow/runstrax.py

Per @SphericalCowww's request.

Added s1_cnn into processing chain

---

outsource/workflow/combine.py

Implemented @dachengx's suggestion to check chunk length & chunk `n` in metadata before uploading in combine jobs. This is a trial in solving #75 using #85.

Loading check

---

bin/outsource
outsource/RunConfig.py
outsource/workflow/runstrax.py

So we save a lot more efforts in reprox

Added event_ambience and event_shadow

---

outsource/Outsource.py

Removed hardcode Dakota

---

outsource/RunConfig.py
outsource/workflow/combine.py
outsource/workflow/runstrax.py

Temporary. Will put back once the correction is available.

removed s1_cnn temporarily

---

outsource/workflow/pegasus.conf

Try to speed up. Not sure it's gonna work but it doesn't hurt to have it.

More maxidle

---

outsource/workflow/combine.py
outsource/workflow/runstrax.py

Timing info for admix.upload

---

outsource/workflow/runstrax.py

Forbid multi-threading

---

outsource/workflow/runstrax.py

Still don't have a good solution though. Let's try giving more debug info first.

Debug info for mismatch between chunks and metadata

---

outsource/workflow/runstrax.py

Triggered by @cfuselli. Thanks!

Not to updatedb if upload failed

---

outsource/workflow/runstrax.py

Trying to add `cuts_basic` into to-process list

---

outsource/Outsource.py
outsource/workflow/runstrax.py
outsource/workflow/strax-wrapper.sh

So that at least we can have the output somewhere locally accessible when rucio is not working.

Added output for events jobs

---

README.md
outsource/Outsource.py
outsource/workflow/combine.py
outsource/workflow/runstrax.py
outsource/workflow/strax-wrapper.sh

Just because the afterpulses branch has been so outdated...

Merge master into afterpulse debugging

---

README.md
bin/outsource
outsource/Outsource.py
outsource/workflow/combine.py
outsource/workflow/runstrax.py
outsource/workflow/strax-wrapper.sh

Still cannot get it work because of #130, but we did several minor things worth merging.

Given up afterpulses computation but doesn't hurt to merge

---

outsource/Outsource.py

To see if we can avoid the consistency issue suspected to be rooted in numba.

Try requiring AVX2 only

---

outsource/workflow/strax-wrapper.sh

So we can see if the RunDB API is accessible

echo Rundb api accessibility

---

bin/outsource

Not sure why, but this block seems forcing us into the `peak_se_density` missing problem. Somehow it got unregistered.

Removed outdated cuts removal

---

outsource/Outsource.py

Removed outdated plugin unregister

---

outsource/Outsource.py

Untested, but this should help with all the gfal2 DeprecationWarning noise.

Improved logging when using gfal2

---

outsource/Outsource.py

Since it seems that we don't have allocation at CNAF anymore.

Remove CNAF from glidein site specificiation

---

bin/outsource
outsource/config.py
outsource/outsource.py
outsource/workflow/combine-wrapper.sh
outsource/workflow/combine.py
outsource/workflow/process-wrapper.sh
outsource/workflow/process.py
outsource/workflow/upload.py

Add more options for job submission

---

pyproject.toml

We need this PR: https://github.com/XENONnT/utilix/pull/130

Bump version of utilix

---

outsource/submitter.py

To solve the issue https://github.com/XENONnT/outsource/issues/184

add timestamp to workflow

---

outsource/submitter.py

Close: https://github.com/XENONnT/outsource/issues/187

Download log of jobs

---

outsource/submitter.py
outsource/workflow/untar.sh

Close: https://github.com/XENONnT/outsource/issues/195

Untar outpus if transferred to local

---

outsource/upload.py

Close: https://github.com/XENONnT/admix/issues/56
Depends on https://github.com/XENONnT/admix/pull/57

Upload miscellaneous information to DB

---

README.md
outsource/submitter.py
outsource/workflow/process-wrapper.sh
outsource/workflow/process.py

Close: https://github.com/XENONnT/outsource/issues/188

Ignore processed data while processing

---

outsource/config.py
outsource/submitter.py

Close: https://github.com/XENONnT/outsource/issues/166
Close: https://github.com/XENONnT/outsource/issues/185

Clearly list the `data_type` to process when submitting job

---

outsource/submitter.py

and make the workflow_id different
Close: https://github.com/XENONnT/outsource/issues/207

If self-installed package, do not upload to rucio

---

outsource/submitter.py

Because outsource transfer files from local to davs.
Otherwise you will see error like:
```
2024-10-14 00:34:17,992   ERROR:  Command exited with non-zero exit code (13): gfal-copy -f -p -t 7200 -T 7200 'file:///home/xudc/outsource/outsource/workflow/process-wrapper.sh' 'davs://xenon-gridftp.grid.uchicago.edu:2880/xenon/scratch/xudc/user-el9.2024.09.1-xenonnt_offline-global_v16-050775-202410140025/runs/00/00/upper_tpc'
```
The bug was introduced by https://github.com/XENONnT/outsource/pull/194.

Still need local sites even if do not transfer to local

---

outsource/submitter.py

Related [slack thread](https://xenonnt.slack.com/archives/C07BT5HD6NB/p1728909850326229)

Set defualt `dagman_maxjobs` to be 5000

---

outsource/utils.py

Fix $lte for single run

---

outsource/config.py
outsource/meta.py

Close: https://github.com/XENONnT/outsource/issues/218

No per-chunk processing of MV

---

README.md
outsource/scripts/submit.py
outsource/submitter.py
outsource/workflow/combine-wrapper.sh
outsource/workflow/combine.py
outsource/workflow/process-wrapper.sh
outsource/workflow/process.py
outsource/workflow/test_resource_usage.py

You will get extra files for each job:
1. `.npy` of memory usage vs time
2. `.json` of the time used for processing each `data _type`
3. `.json` of detailed storage occupation of each directory

Add script to test the resources usage: memory, time, storage

---

outsource/config.py
outsource/workflow/combine-wrapper.sh
outsource/workflow/process-wrapper.sh
outsource/workflow/process.py

I do not know the reason, but when using ` --remove-files`, I see
```
gzip: stdin: invalid compressed data--crc error
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
When untar the tarball in higher level jobs.

Keep the folder being tarred

---

outsource/config.py
outsource/meta.py
outsource/submitter.py
outsource/utils.py
outsource/workflow/process.py
outsource/workflow/test_resource_usage.py

Depends on PR: https://github.com/XENONnT/straxen/pull/1482.
We want to process `peaklet_position_*` in per-chunk (lower level) processing to save calendar time.

Allow multiple per-chunk processing

---

outsource/config.py
outsource/submitter.py

After a thorough test, we will add these back.
https://github.com/XENONnT/outsource/pull/244
https://github.com/XENONnT/outsource/pull/245

Revert part of #244 and #245

---

outsource/config.py
outsource/meta.py

```
k = 0.006 +- 0.001 GB/GB
b = 3.580 +- 0.299 GB
```

Update memory usage of upper level jobs

---

outsource/scripts/submit.py
outsource/submitter.py
outsource/utils.py
outsource/workflow/combine-wrapper.sh
outsource/workflow/combine.py
outsource/workflow/process-wrapper.sh
outsource/workflow/process.py

Depends on https://github.com/XENONnT/straxen/pull/1520
The `--stage` option is not recommended for large-scale processing but is OK for debugging and testing small-scale runs.

Add option to first stage the rucio files then download

---

README.md
outsource/config.py
outsource/meta.py
outsource/workflow/process.py

Depends on https://github.com/AxFoundation/strax/pull/975 and https://github.com/AxFoundation/strax/pull/976

Update memory usage after optimization

---

outsource/scripts/submit.py
outsource/submitter.py
outsource/utils.py
outsource/workflow/combine-wrapper.sh
outsource/workflow/combine.py
outsource/workflow/process-wrapper.sh
outsource/workflow/process.py

Remove downloaded heavy chunks right after loading

Be compatible with https://github.com/XENONnT/straxen/pull/1570

---

outsource/config.py

because raw_records* will be deleted immediately after loaded.
Depends on https://github.com/XENONnT/straxen/pull/1570

Only have to consider the largest chunk size of `raw_records*`

---

outsource/utils.py

The old PR https://github.com/XENONnT/outsource/pull/308 forgot to overwrite the storage.

Fix bug of missing overwritten storage

---

README.md
outsource/config.py
outsource/meta.py
outsource/scripts/submit.py
outsource/utils.py
outsource/workflow/combine.py
outsource/workflow/process.py

Compatible with saltax 5c42db5a41690215f9245472a9e690faac91db2d

Saltax compatibility

---

outsource/submitters/slurm.py

Depends on https://github.com/XENONnT/saltax/pull/203

Save the instruction before submitting jobs
